SELECT HR.EMPLOYEES.FIRST_NAME,
  HR.EMPLOYEES.LAST_NAME,
  COUNT(ORDERS.ORDER_ID)                 AS Count_ORDER_ID,
  SUM(ORDERS.ORDER_TOTAL)                AS Sum_ORDER_TOTAL,
  COUNT(DISTINCT CUSTOMERS.CUSTOMER_ID)  AS Count_CUSTOMER_ID,
  COUNT(DISTINCT ORDER_ITEMS.PRODUCT_ID) AS Count_PRODUCT_ID
FROM ORDERS
INNER JOIN ORDER_ITEMS
ON ORDERS.ORDER_ID = ORDER_ITEMS.ORDER_ID
INNER JOIN CUSTOMERS
ON CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
INNER JOIN HR.EMPLOYEES
ON HR.EMPLOYEES.EMPLOYEE_ID = ORDERS.SALES_REP_ID
GROUP BY HR.EMPLOYEES.FIRST_NAME,
  HR.EMPLOYEES.LAST_NAME